### ISSUE TITLE
Call to undefined function get_form_tags(

### ISSUE THREAD

**Issue by sagredo-dev** [johndoh/roundcube-sauserprefs#66]
sauserprefs v.1.19 against rc-1.5.1 ends up with this error

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_form_tags() in /usr/local/www/htdocs/roundcubemail-1.5.1/plugins/sauserprefs/sauserprefs>
Stack trace:
#0 /usr/local/www/htdocs/roundcubemail-1.5.1/program/include/rcmail_output_html.php(1484): sauserprefs->gen_form()
#1 [internal function]: rcmail_output_html->xml_command()
#2 /usr/local/www/htdocs/roundcubemail-1.5.1/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#3 /usr/local/www/htdocs/roundcubemail-1.5.1/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#4 /usr/local/www/htdocs/roundcubemail-1.5.1/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#5 /usr/local/www/htdocs/roundcubemail-1.5.1/plugins/sauserprefs/sauserprefs.php(157): rcmail_output_html->send()
#6 /usr/local/www/htdocs/roundcubemail-1.5.1/program/lib/Roundcube/rcube_plugin_api.php(570): sauserprefs->init_html()
#7 /usr/local/www/htdocs/roundcubemail-1.5.1/program/include/rcmail.php(248): rcube_plugin_api->exec_actio in /usr/local/www/htdocs/roundcubemail-1.5.1/plugins/sauserprefs/sauserprefs.php >
```

**Comment by johndoh** [comment]
The global function get_form_tags was removed in Roundcube 1.5 and replaced with rcmail_action::get_form_tags so I think you are not actually running sauserprefs 1.19 but 1.18 or earlier which is not compatible with Roundcube 1.5.
